feature : CitynameMapping
cs-kmitl-2017/group3 pull request #12
Opened 2017-12-08 15:48 UTC by PhatipanSuwanich

2017-12-08 17:15 UTC, champillon requested changes
ฝากชี้แจงด้วยครับ

2017-12-08 17:15 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/CityName.java
> +            default : return 0;
ทำไม default ตอ้ง return 0 อ่ะ ทำไมไม่ throw Exception

2017-12-09 06:24 UTC, PhatipanSuwanich commented on src/main/java/th/ac/kmitl/science/comsci/example/models/CityName.java
> +            default : return 0;
เพิ่ม throw Exception แล้วนะครับ comment ผมก่อนหน้าเหมือนผมกดผิดไปกดลบ

2017-12-09 06:29 UTC, champillon requested changes
แก้มาด้วยนะครับ เขียนโปรแกรมให้สื่อความหมาย ให้เพื่อนทำงานต่อได้ง่าย ไม่ใช่เขียนโปรแกรมตามที่พี่บอกครับ

2017-12-09 06:29 UTC, champillon commented on src/main/java/th/ac/kmitl/science/comsci/example/models/CityName.java
> +            default : throw new Exception();
กรรมส์ Exception ช่วยตั้งใส่สื่อหน่อยครับ เช่น MappingNotFoundException อะไรแบบนี้ครับ

2017-12-09 07:39 UTC, PhatipanSuwanich commented
แก้แล้วนะครับ ผมเข้าใจถูกหรือป่าวครับ

2017-12-09 08:32 UTC, champillon approved these changes
LGTM la

2017-12-09 09:52 UTC, thebankky approved these changes
LGTM

2017-12-09 10:07 UTC, merged