Create ModelCompany By Pattharachat
cs-kmitl-2017/group3 pull request #7
Opened 2017-12-07 14:32 UTC by Pattharachat

2017-12-07 14:56 UTC, champillon commented
@Pattharachat ทำไมทำ PR มาซ้ำกันหล่ะครับ???

2017-12-07 16:46 UTC, champillon requested changes
LGTM la

2017-12-07 16:54 UTC, thebankky approved these changes
LGTM

2017-12-07 17:03 UTC, Pattharachat commented
หนูต้องไปเพิ่มอะไรอีกมั้ยค่ะ

2017-12-07 17:07 UTC, champillon commented
ไป close PR ที่ duplicate อีกอันซึ้งไม่ได้ใช้ก่อนครับถึง merge ให้

2017-12-07 17:53 UTC, Pattharachat commented
close PR เรียบร้อยแล้วค่ะ

2017-12-08 01:11 UTC, champillon approved these changes
LGTM la

2017-12-08 01:17 UTC, champillon commented
ตัด
1. component (1 คะแนน) => ยังไม่ได้ใช้อะไรยาก เลยให้ได้แค่ 1 คะแนน

2. naming & convention (1 คะแนน) => ไม่มีอะไรหัก

3. technologies (0 คะแนน) => ไม่มีอะไรยาก ไม่ให้คะแนน

4. git usage (0.5 คะแนน) =>
- 0.25 เพราะทำ PR ซ้ำ
- 0.25 เพราะ

2017-12-08 02:08 UTC, thebankky approved these changes
LGTM law krub

2017-12-08 02:13 UTC, khemtat requested changes

2017-12-08 02:13 UTC, khemtat commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Compony.java
> +
คลาสชื่อ Company แต่ไฟล์ชื่อ Compony.java ฝากแก้นิดนึงนะครับ

2017-12-08 02:13 UTC, khemtat commented on src/main/java/th/ac/kmitl/science/comsci/example/models/Compony.java
> +    private String globolId;
global พิมพ์ผิดนะครับ globolId -> globalId

2017-12-08 10:17 UTC, champillon requested changes
ฝากแก้ด้วยครับ

2017-12-08 10:17 UTC, champillon commented on src/test/java/th/ac/kmitl/science/comsci/example/models/CompanyTest.java
> +    public void TestInputCompany() {
ชื่อ method ขึ้นต้นเป็นตัวเล็กครับ

2017-12-08 10:18 UTC, khemtat approved these changes

2017-12-08 10:18 UTC, champillon commented
อันนี้ merge ไปแล้วหนิครับ แก้กลับมาทำไปอีก พี่ปิดนะครับ

2017-12-08 10:19 UTC, closed without merging